---
- name: Ensure Jenkins is Running and Cleanup Docker Images
  hosts: localhost
  become: yes
  tasks:
    - name: Ensure Jenkins Container is Running
      shell: |
        if ! docker ps --filter "name=jenkins" --format "{{.Names}}" | grep -q jenkins; then
          echo "Jenkins is not running. Starting now..."
          docker start jenkins || docker run -d --name jenkins --restart always -p 9090:8080 jenkins/jenkins:lts
          sleep 10  # Wait for Jenkins to be fully up
        else
          echo "✅ Jenkins is already running."
        fi

    - name: Remove Old "final-guestbook" Images
      shell: |
        docker images | awk '$1 ~ /final-guestbook/ { print $3 }' | xargs -r docker rmi
