- name: Ensure Jenkins is Running and Cleanup Docker Images
  hosts: localhost
  gather_facts: yes
  tasks:

    - name: Ensure Jenkins container is running
      shell: |
        docker ps --filter "name=jenkins" --format "{{.Names}}" | grep -q "jenkins" || \
        docker start jenkins
      register: jenkins_status
      changed_when: jenkins_status.rc != 0

    - name: List old Docker images
      command: docker images -f "dangling=true" -q
      register: old_images
      changed_when: old_images.stdout != ""

    - name: Remove old Docker images
      command: docker rmi -f {{ item }}
      loop: "{{ old_images.stdout_lines }}"
      when: old_images.stdout_lines | length > 0
