---
- name: Deploy The Final Project
  hosts: localhost
  become: yes
  tasks:

    - name: Start Docker Service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Ensure Jenkins is Running
      shell: |
        docker ps | grep jenkins || docker run -d --name jenkins --restart=always -p 9090:8080 -v jenkins_home:/var/jenkins_home jenkins/jenkins:lts

    - name: Stop Existing Application
      shell: |
        docker stop the-final-project-guestbook-web || true
        docker rm the-final-project-guestbook-web || true

    - name: Pull Latest Image
      shell: docker pull ahmedelshandidy/the-final-project-guestbook-web:latest

    - name: Run Application on Port 5000
      shell: >
        docker run -d --name the-final-project-guestbook-web
        -p 5000:5000
        --restart=always
        ahmedelshandidy/the-final-project-guestbook-web:latest
